### ISSUE TITLE
Alerts don't trigger emails

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#114]
Earlier Henri reported:

I have been testing now alerts via gateway, so far it doesn't work very well.
I don't get movement alerts via email and for temperature I get email alert only one time when it's activated.
For example today around 13.50-14.15 temperature went higher than 5C and I didn't get any email.

Sami replied:

Thanks for letting me know - maybe there's an issue with resetting the alert state when it goes back under the limit. Will check - will also check movement alerts - there are tests for it so it might be an issue with the actual email sending part rather than triggering the alert... ...On Henri's point from earlier, I found at least one issue with the emails (already fixed on local, but need to test properly), I'm still testing through it and adding tests for resetting alerts.

Now I'm testing alerts and they don't trigger any emails.

Example: I have a sensor in the cloud that's showing 19,50C temperature now. Then I want to test the alerts and I'm configuring on my Ruuvi Station "alert if less than 10C or more than 18C. Then I wait 1 minute, sync the app with the network, I see correctly the alarm bell ringing on the app. But I get no email.

Then I created an alarm "alert if less than 10C or more than 20C" and then heated up the sensor so that its temperature increased from 19,50C to 21,50C. Alert triggered ok on the app (the bell icon) but I received no email.

**Comment by laurijamsa** [comment]
Now I got an alert email of the first test. About an hour after it was supposed to be sent.

**Comment by io53** [comment]
https://github.com/ruuvi/ruuvi-network-serverless/issues/112
Is probably the same issue

**Comment by laurijamsa** [comment]
Sami on Slack: "The e-mails should be fixed. Still looking into movement alert resets and having a proper test in place to test it. One thing of note was that we added a once per hour filter there for production environment to avoid spamming, so that could be part of the issue of not seeing it - we can reduce it to something shorter."

I'm testing now the alert feature and I cannot get it working.

I set to alert when more than 21C and then heating up the sensor to 21,20C and alert doesn't trigger. It triggers via bluetooth just fine. Now I cannot even see red color on the web ui like before the new cloud deployment.

![image](https://user-images.githubusercontent.com/1311912/130010776-3136bf60-fc3d-40bf-b660-bfdcaedcaa84.png)

**Comment by Muhwu** [comment]
Please let me know if you have any delays. Currently the only delay that could imbue _should be_ the 1h delay between alerts.

**Comment by markoaamunkajo** [comment]
I don't see delays at least for 24 hours now.

**Comment by markoaamunkajo** [comment]
Movement alert was set, synced to network and triggered but it didn't trigger email, so looks like this issue still persists.

**Comment by laurijamsa** [comment]
Same here. I'm not getting an email when movement alert triggers.

**Comment by io53** [comment]
+1 Stopped getting movement email. It does show up as triggered in /alerts as it should

**Comment by io53** [comment]
I set a temperature alarm >25C, and I'm getting email alert for temperature every hour even tho the temperature has not gone below the setpoint.

**Comment by laurijamsa** [comment]
Alerts are working for me and didn't notice issues this time. Closing this one for now, but feel free to reopen if needed.

**Comment by markoaamunkajo** [comment]
Confirmed alerts triggering emails now.
